### ISSUE TITLE
Simplified Menu Concept

### ISSUE THREAD

**Issue by zipatton** [MuhXd/BetterMenuMod#5]
## Just a concept for an option that makes it more simplified.
![20240307134701_1](https://github.com/MuhXd/BetterMenuMod/assets/155669622/eb4e96e3-fdc9-4bd6-ad95-fa78dccd410a)
_Done by changing the position of things with Dev Tools_

**Comment by Cosmella-v** [comment]
this looks like a cool idea! i will consider adding it

**Comment by Cosmella-v** [comment]
@zipatton i'm gonna upload a almost finished build of what was described with extra features

**Comment by Cosmella-v** [comment]
![image](https://github.com/MuhXd/BetterMenuMod/assets/100521306/27afd1f3-b9ac-4eb1-8a32-dbef1674cfa0)

**Comment by Cosmella-v** [comment]
![image](https://github.com/MuhXd/BetterMenuMod/assets/100521306/43b13cab-ec54-45fb-8ae5-6b375bb78ce9)
