### ISSUE TITLE
Suggestion: allow for turning shortcuts into button on the bottom row

### ISSUE THREAD

**Issue by Hanifinio** [MuhXd/BetterMenuMod#6]
I can imagine it looking a bit cleaner.
![Screenshot_20240311_060757_Geode](https://github.com/MuhXd/BetterMenuMod/assets/162050629/0a0c9b25-da76-47c2-8a6e-bc4e36db1f3a)

**Comment by Cosmella-v** [comment]
@Hanifinio i am close to finishing

**Comment by Hanifinio** [comment]
Yo lets go
