### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by Helloausername** [MuhXd/BetterMenuMod#7]
When press the quote button (a mod) it crashes and when you turn the option merp on in better menu settings it crashes when leaving the better menu settings

android 32bit

quote crashlog if needed? 
[Crash 2024-03-18 18.26.03.dmp](https://github.com/MuhXd/BetterMenuMod/files/14639584/Crash.2024-03-18.18.26.03.dmp)

merp crashlog
[Crash 2024-03-18 18.31.35.dmp](https://github.com/MuhXd/BetterMenuMod/files/14639596/Crash.2024-03-18.18.31.35.dmp)

**Comment by Cosmella-v** [comment]
This is a quotes bug so i cannot fix this, i am sorry
